name: Build

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2     
    - uses: actions/checkout@v2
    
    - name: NuGet PKG Restore
      run: msbuild -t:restore src/Orangebeard.Client/Orangebeard.Client.sln
    
    - name: Build
      run: msbuild
    
    - name: Test
      run: dotnet test 