name: Build DLL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - uses: actions/checkout@v2
    
    - name: Build
      run: msbuild src/Orangebeard.Client/Orangebeard.Client.sln
