name: Build DLL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - uses: actions/checkout@v2
    - name: NuGet PKG Restore
      run: msbuild -t:restore src/Orangebeard.Client/Orangebeard.Client.sln
    - name: Build
      run: msbuild src/Orangebeard.Client/Orangebeard.Client.csproj /p:Configuration=Release /p:NoWarn=1591
